kind: PersistentVolume
apiVersion: v1
metadata:
  name: shared-pv1
  labels:
    type: local
    name:  sharedvolume
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc1
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      name:  sharedvolume